### PR TITLE
#154921984 feat: create witnesses model

### PR DESCRIPTION
**Pull request by Mercy-Muchai**
#### What does this PR do?
creates witnesses model
#### Description of Task to be completed?
- add relationships with other tables
(witnesses belong to incidents & users tables)
- rm witnesses column from incidents table
#### How should this be manually tested?
`npm run postinstall`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[154921984](https://www.pivotaltracker.com/story/show/154921984)
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by bmuthoga** [comment]
LGTM, although I've noticed the `Incidents model` doesn't have the `primary key id` defined.

**Comment by Mercy-Muchai** [comment]
@bmuthoga It does have one. Do you mean you cannot see it defined in the model file? It's automatically created in migrations by sequelize as an `autoincrement INTEGER` versus having it in the model. We define it in the model when we want it to take different attributes versus the default. e.g in `Users model` we needed it to be a unique string. Also, do you think we need the `id` field in `Witnesses` model? Given that some of the witnesses will be reused from the `Users model`? cc: @Mnickii

**Comment by Mnickii** [comment]
LGTM

**Comment by bmuthoga** [comment]
OK I see. 

I think it would be good to have one. What do you have in mind? cc: @Mnickii

**Comment by Mnickii** [comment]
The id identifier for the witnesses is essentially the user_id, since a witness is a user. Given that there can be more than one witness to an incident, the table is necessary, but the id should be the user_id. There is no need for another identifier.

**Pull request merged**
