### PR TITLE
Setup project for docker builds and deployment.

### PR DESCRIPTION
**Pull request by nyambati**
#### What does this PR do?
- Move the application source code to src folder
- Add docker  compose for local development environment
- Modify `.circleci/config.yml` to accept the current change of direcory and deployment scripts
- Add deployement script to build and deploy images to kubernetes.

#### Description of Task to be completed?
The current changes update the CI pipeline and deployment scripts to allow docker builds and deployment to k8s cluster on staging and master branch. With this setup, it will be easier to make releases on staging branch, test the functionality before releasing them to production.
#### Files to review
[config.yml](https://github.com/AndelaOSP/wire-api/pull/101/files#diff-1d37e48f9ceff6d8030570cd36286a61)
[Dockerfile](https://github.com/AndelaOSP/wire-api/pull/101/files#diff-d187d630242534e2ddc3aec11f37fd98)
[docker compose](https://github.com/AndelaOSP/wire-api/pull/101/files#diff-c9ed90ca6414e2ed700ee120e5b55382)
[deployment script](https://github.com/AndelaOSP/wire-api/pull/101/files#diff-93518fda10b0403d3c5c20b4df4740a6)
#### What are the relevant pivotal tracker stories?
Finishes[#157435830](https://www.pivotaltracker.com/story/show/157435830)

### CODE REVIEW

**Comment by kimobrian** [comment]
@nyambati Sync with @RayNjeri to help fixing the conflicts and have everything working as expected.

**Comment by nyambati** [comment]
@kimobrian I am currently syncing changes from staging seems like branched with outdated changes. I will sync with her tomorrow to ensure I did not break anything.

**Comment by nyambati** [comment]
@RayNjeri did we review this? if not remind me we look into it tomorrow.

**Comment by RayNjeri** [comment]
@nyambati no we didn't

**Comment by nyambati** [comment]
ok, I will find you so that we can make a full review.

**Pull request merged**
